version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    parameters:
      img:
        type: string
    machine:
      image: <<parameters.img>>
    parallelism: 3
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install required packages
          command: .circleci/install-pkgs-ubuntu.sh

workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              img:
                - "ubuntu-2204:2022.04.1"
                - "ubuntu-2004:2022.04.1"
                - "ubuntu-2004:202111-02"
                - "ubuntu-2004:202201-02"
